FROM python:3.9-slim

WORKDIR /app

COPY src/p2p.py ./p2p.py

# Currently only expose these three ports as available for the peer clients to connect to
EXPOSE 6001 6002 6003

CMD ["python3", "p2p.py"]